// @todo make this a file generated by the api itself

import { Models } from "../api-sdk/models";

export const getIconFromStatus = (status: Models.Book.Status) => {
  switch (status) {
    case Models.Book.Status.Reading: {
      return "fas fa-eye";
    }
    case Models.Book.Status.Borrowing: {
      return "fas fa-file-import";
    }
    case Models.Book.Status.Lending: {
      return "fas fa-file-export";
    }
    case Models.Book.Status.Read: {
      return "fas fa-check";
    }
    case Models.Book.Status.Gift: {
      return "fas fa-gifts";
    }

    // unread is the absence of read, and less important than other statuses
    default: {
      return "fas fa-eye-slash";
    }
  }
};

export const getDescriptionFromStatus = (status: Models.Book.Status) => {
  switch (status) {
    case Models.Book.Status.Reading: {
      return "Currently reading";
    }
    case Models.Book.Status.Borrowing: {
      return "Borrowed";
    }
    case Models.Book.Status.Lending: {
      return "Lending";
    }
    case Models.Book.Status.Read: {
      return "Already read";
    }
    case Models.Book.Status.Gift: {
      return "A gift";
    }

    // unread is the absence of read
    default: {
      return "Unread";
    }
  }
};
